#!/bin/zsh
##? substenv - substitutes string parts with environment variables
if (( $# == 0 )); then
  subenv ZDOTDIR | subenv HOME
else
  local sedexp="s|${(P)1}|\$$1|g"
  shift
  sed "$sedexp" "$@"
fi
